project:
  type: website

website:
  navbar:
    left:
      - icon: house-door-fill 
        href: index.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/zina29k/medical_data_exploration
        
format:
  html:
    theme: cosmo
    css: styles.css